### PR TITLE
[babel] upgrade to babel@6

### PR DESCRIPTION
**Pull request by oliviertassinari**
Fix https://github.com/oliviertassinari/babel-plugin-react-remove-properties/issues/2.

### CODE REVIEW

**Comment by oliviertassinari** [comment]
@ovaris Can you try this PR?

**Comment by ovaris** [comment]
Coupe of issues I had: I ran `npm build` inside `node_modules/babel-plugin-react-remove-properties` which copies `src` folder under `lib`, so it ended up `lib/src/index.js` instead of `lib/index.js`. After manually moving it `lib/index.js`, I got following error:

```
SyntaxError: /Users/ollivaris/programming/nextgen/site/components/DefaultRouteHandler/index.js: NodePath has been removed so is read-only. (This is an error on an internal node. Probably an internal error)
    at File.buildCodeFrameError (/Users/ollivaris/programming/nextgen/node_modules/babel-core/lib/transformation/file/index.js:407:15)
    at NodePath.buildCodeFrameError (/Users/ollivaris/programming/nextgen/node_modules/babel-traverse/lib/path/index.js:148:26)
    at NodePath._assertUnremoved (/Users/ollivaris/programming/nextgen/node_modules/babel-traverse/lib/path/removal.js:67:16)
    at NodePath.remove (/Users/ollivaris/programming/nextgen/node_modules/babel-traverse/lib/path/removal.js:17:8)
    at PluginPass.visitor.JSXIdentifier (/Users/ollivaris/programming/nextgen/node_modules/babel-plugin-react-remove-properties/lib/index.js:8:27)
    at newFn (/Users/ollivaris/programming/nextgen/node_modules/babel-traverse/lib/visitors.js:276:19)
    at NodePath._call (/Users/ollivaris/programming/nextgen/node_modules/babel-traverse/lib/path/context.js:74:18)
    at NodePath.call (/Users/ollivaris/programming/nextgen/node_modules/babel-traverse/lib/path/context.js:46:17)
    at NodePath.visit (/Users/ollivaris/programming/nextgen/node_modules/babel-traverse/lib/path/context.js:104:12)
    at TraversalContext.visitQueue (/Users/ollivaris/programming/nextgen/node_modules/babel-traverse/lib/context.js:153:16)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by oliviertassinari** [comment]
I'm gonna fix this cp issue.
Regarding the other issue. I think that it's from this line https://github.com/babel/babel/blob/0708edb92720569fea83be63281cd4d3ab217553/packages/babel-traverse/src/path/removal.js#L56. That's weird because I don't have it with my simple test case.

**Comment by ovaris** [comment]
Yes,

```
babel-plugin-react-remove-properties git:(master) ✗ npm run build

> babel-plugin-react-remove-properties@0.2.0 build /Users/ollivaris/programming/nextgen/node_modules/babel-plugin-react-remove-properties
> rm -rf lib && mkdir lib && babel src --out-dir lib

src/index.js -> lib/index.js
➜  babel-plugin-react-remove-properties git:(master) ✗ npm test

> babel-plugin-react-remove-properties@0.2.0 test /Users/ollivaris/programming/nextgen/node_modules/babel-plugin-react-remove-properties
> istanbul test _mocha



  remove react propTypes
    ✓ should simple


  1 passing (340ms)
```

**Comment by oliviertassinari** [comment]
@ovaris Could this be because my tests are too simple?

**Comment by ovaris** [comment]
Could be, I don't quite understand that error. Do you use this plugin in some project?

**Comment by oliviertassinari** [comment]
@ovaris I do (https://splitme.net). But I'm still using babel@5. I will try to use this PR on my project. Stay tuned

**Comment by ovaris** [comment]
Cool. Thanks, I will.

**Comment by oliviertassinari** [comment]
I'm merging this PR since the test passed. But I won't release until we have a better green test suit

**Pull request merged**
